### ISSUE TITLE
主题切换功能【需求】

### ISSUE THREAD

**Issue by helingjuan** [heihuahe/lingBook#17]
通过css变量:root实现，且不能影响已有项目的css变量

```css
:root[data-theme="light"] {
 --mian-color: #ffffff;
}

:root[data-theme="red"] {
 --mian-color:  red;
}
```

```js
document.documentElement.setAttribute('data-theme', 'light')
```
